version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/packages/app-main'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/packages/app-main-e2e'
    schedule:
      interval: 'monthly'
  - package-ecosystem: 'npm'
    directory: '/packages/api-main'
    schedule:
      interval: 'monthly'
