apiVersion: v1
kind: LimitRange
metadata:
  name: namespace-limit-range
  namespace: pintask
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 512Mi
      defaultRequest:
        cpu: 200m
        memory: 256Mi
      max:
        cpu: '2'
        memory: 2Gi
